Export GPG_TTY
The variable tells pinentry-curses where to prompt for password.
Otherwise Git commit signing breaks with:

error: gpg failed to sign the data
fatal: failed to write commit object

This doesn't seem to be the problem for other programs that use GPG like
pass.